#!/bin/bash

echo "==================================================================="
echo "Mouse Tracking Cleanup - Debug Test"
echo "==================================================================="
echo ""
echo "This will run the demo with debug logging to show exactly what"
echo "happens during cleanup when you press Ctrl+C."
echo ""
echo "Instructions:"
echo "  1. The demo will start"
echo "  2. Navigate to 'Bar Chart' (optional - mouse tracking is always enabled)"
echo "  3. Press Ctrl+C"
echo "  4. Watch for [CLEANUP] and [SIGNAL] debug messages"
echo "  5. After exit, scroll mouse wheel to test"
echo ""
echo "Press Enter to start..."
read

echo ""
echo "Starting demo (watch for cleanup messages when you press Ctrl+C)..."
echo "==================================================================="
dune exec -- miaou.demo

echo ""
echo "==================================================================="
echo "Demo exited. Check the output above for:"
echo "  - [SIGNAL] messages (signal handler ran)"
echo "  - [CLEANUP] messages (cleanup steps)"
echo "  - Did sleep complete?"
echo ""
echo "Now scroll your mouse wheel:"
echo "  - Normal scrolling = ✓ FIXED"
echo "  - 'unbound keyseq: mouse' = ✗ Still broken"
echo "==================================================================="
