#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Upload GIF screencasts under recordings/ to a GitLab Merge Request.

Environment:
  GITLAB_API_TOKEN        – private token with API scope (required)
  CI_PROJECT_ID           – numeric project id (required)
  CI_MERGE_REQUEST_IID    – MR IID; if missing the script tries to locate an
                             open MR matching CI_COMMIT_REF_NAME.
  GITLAB_API              – optional base URL (default: https://gitlab.com/api/v4)

The script looks for `recordings/*.gif`, uploads each via the project uploads
API, and posts a single MR note listing the embedded GIFs. A local `uploaded.md`
file stores the markdown even if posting fails.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import requests


def log(msg: str) -> None:
    print(msg)


def main() -> int:
    token = os.environ.get("GITLAB_API_TOKEN")
    project_id = os.environ.get("CI_PROJECT_ID")
    mr_iid = os.environ.get("CI_MERGE_REQUEST_IID")
    gitlab_api = os.environ.get("GITLAB_API", "https://gitlab.com/api/v4")

    if not token:
        log("GITLAB_API_TOKEN missing – skipping GIF upload.")
        return 0
    if not project_id:
        log("CI_PROJECT_ID missing – cannot upload to GitLab.")
        return 1

    headers = {"PRIVATE-TOKEN": token}

    if not mr_iid:
        ref = os.environ.get("CI_COMMIT_REF_NAME")
        if not ref:
            log("CI_MERGE_REQUEST_IID missing and branch name unavailable – cannot locate MR.")
            return 0
        try:
            search_url = f"{gitlab_api}/projects/{project_id}/merge_requests"
            params = {"state": "opened", "source_branch": ref}
            resp = requests.get(search_url, headers=headers, params=params, timeout=10)
            resp.raise_for_status()
            matches = resp.json()
            if not matches:
                log(f"No open MR found for branch '{ref}'.")
                return 0
            mr_iid = str(matches[0].get("iid"))
            log(f"Found MR IID {mr_iid} for branch {ref}.")
        except Exception as exc:  # pragma: no cover - best-effort behavior
            log(f"Failed to look up MR for branch '{ref}': {exc}")
            return 0

    recordings_dir = Path("recordings")
    gifs = sorted(recordings_dir.glob("*.gif"))
    if not gifs:
        log("No GIFs found in recordings/ – nothing to upload.")
        return 0

    uploaded_md: list[str] = []

    for gif in gifs:
        log(f"Uploading {gif}…")
        url = f"{gitlab_api}/projects/{project_id}/uploads"
        try:
            with open(gif, "rb") as fh:
                files = {"file": (gif.name, fh, "image/gif")}
                resp = requests.post(url, headers=headers, files=files, timeout=60)
            resp.raise_for_status()
            data = resp.json()
            file_url = data.get("url") or data.get("markdown")

            base = gif.stem
            cast_path = recordings_dir / f"{base}.cast"
            title = base.replace("_", " ").title()
            keystrokes_ref = None
            if cast_path.exists():
                try:
                    header_line = cast_path.read_text(encoding="utf8").splitlines()[0]
                    header = json.loads(header_line)
                    command = header.get("command", "")
                    if command and "--keystrokes" in command:
                        parts = command.split()
                        for idx, token_part in enumerate(parts[:-1]):
                            if token_part == "--keystrokes":
                                keystrokes_ref = parts[idx + 1]
                                title = Path(keystrokes_ref).stem.replace("_", " ").title()
                                break
                except Exception:
                    pass

            if file_url:
                md = f"**{title}**  \n\n![]({file_url})"
            else:
                md = f"**{title}**  \n\n{data!r}"

            if keystrokes_ref:
                md += f"\n\n`Keystrokes: {keystrokes_ref}`"

            uploaded_md.append(md)
            log(f"Uploaded {gif} -> {file_url}")
        except Exception as exc:  # pragma: no cover - network failures
            log(f"Failed to upload {gif}: {exc}")

    if not uploaded_md:
        log("Uploads failed – skipping MR note.")
        return 0

    uploaded_path = Path("uploaded.md")
    uploaded_path.write_text("\n\n".join(uploaded_md), encoding="utf8")
    log(f"Wrote markdown summary to {uploaded_path}")

    details = [
        "<details>",
        "<summary>Miaou TUI capture artifacts (click to expand)</summary>",
        "",
        *uploaded_md,
        "</details>",
    ]
    body = "Artifacts generated by CI pipeline:\n\n" + "\n".join(details)

    notes_url = f"{gitlab_api}/projects/{project_id}/merge_requests/{mr_iid}/notes"
    try:
        note_resp = requests.post(notes_url, headers=headers, data={"body": body}, timeout=30)
        note_resp.raise_for_status()
        log("Posted MR comment with uploaded GIFs.")
    except Exception as exc:  # pragma: no cover - best effort
        log(f"Failed to post MR comment: {exc}")
        log("You can paste uploaded.md manually if needed.")
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
